# Generated by Django 4.0.1 on 2022-01-07 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='biograpy',
            new_name='biography',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='phone_numeber',
            new_name='phone_number',
        ),
    ]
